org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
neo_version=21.1.247
mod_id=advanced_quantum_engineering
mod_name=Advanced Quantum Engineering
mod_version=2.2.4
mod_group=com.syaru.advancedquantumengineering
